obj-$(CONFIG_MSM_CAMERA) += mt9p012_fox.o mt9p012_reg.o mt9t013.o mt9t013_reg.o mt9d112.o mt9d112_reg.o s5k3e2fx.o flash.o
obj-$(CONFIG_ARCH_MSM) += msm_vfe7x.o msm_io7x.o
obj-$(CONFIG_ARCH_QSD) += msm_vfe8x.o msm_vfe8x_proc.o msm_io8x.o 
