obj-$(CONFIG_FSNOTIFY)		+= fsnotify.o notification.o group.o inode_mark.o \
				   mark.o vfsmount_mark.o fdinfo.o

obj-$(CONFIG_DNOTIFY)		+= dnotify/
obj-$(CONFIG_INOTIFY_USER)	+= inotify/
obj-$(CONFIG_FANOTIFY)		+= fanotify/
