/*
	All files except if stated otherwise in the begining of the file are under the ISC license:
	-----------------------------------------------------------------------------------

	Copyright (c) 2010-2012 Design Art Networks Ltd.

	Permission to use, copy, modify, and/or distribute this software for any
	purpose with or without fee is hereby granted, provided that the above
	copyright notice and this permission notice appear in all copies.

	THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
	WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
	MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
	ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
	WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
	ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
	OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/


// NPU_ARM0 global memory areas
// This file is autogenerated from Memory Locator system
// DO NOT EDIT MANUALLY


const unsigned GLOBMEM_TRACE_BUF_ADDR              = 0x40100000;
const unsigned GLOBMEM_TRACE_BUF_SIZE              =     0x3000;

const unsigned GLOBMEM_IPC_AGENT_BUF_ADDR          = 0x404F1000;
const unsigned GLOBMEM_IPC_AGENT_BUF_SIZE          =     0x2000;

const unsigned GLOBMEM_ASSERT_REASON_ADDR          = 0x404F3000;
const unsigned GLOBMEM_ASSERT_REASON_SIZE          =     0x1000;

const unsigned GLOBMEM_EXCEPTION_REASON_ADDR       = 0x404F4000;
const unsigned GLOBMEM_EXCEPTION_REASON_SIZE       =      0x200;

const unsigned GLOBMEM_DEBUG_LEVEL_ADDR            = 0x404FFF80;
const unsigned GLOBMEM_DEBUG_LEVEL_SIZE            =       0x20;

const unsigned GLOBMEM_PLATFORM_ARRAY_TX_ADDR      = 0x404FFFC0;
const unsigned GLOBMEM_PLATFORM_ARRAY_TX_SIZE      =       0x20;

const unsigned GLOBMEM_SYNC_ARRAY_TX_ADDR          = 0x404FFFE0;
const unsigned GLOBMEM_SYNC_ARRAY_TX_SIZE          =       0x20;

const unsigned GLOBMEM_TMR_DB_ADDR                 = 0x60444000;
const unsigned GLOBMEM_TMR_DB_SIZE                 =      0x200;

