obj-$(CONFIG_DANIPC) :=		danipc.o

danipc-objs :=		danipc_main.o		\
			danipc_ioctl.o		\
			danipc_data.o		\
			danipc_lowlevel.o	\
			IPC_trns_fifo.o		\
			IPC_cfg.o		\
			IPC.o			\
			danipc_wq.o

EXTRA_CFLAGS +=		-DUNIX
